#!/bin/sh
set -e

# Automatically update the GTK icon cache after install
if [ "$1" = "configure" ]; then
    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -f /usr/share/icons/hicolor || true
    fi
fi

exit 0